// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// generateSamples
List generateSamples(NumericVector thetas, int numberOfReplicates, int seed);
RcppExport SEXP abcProject_generateSamples(SEXP thetasSEXP, SEXP numberOfReplicatesSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type thetas(thetasSEXP);
    Rcpp::traits::input_parameter< int >::type numberOfReplicates(numberOfReplicatesSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    __result = Rcpp::wrap(generateSamples(thetas, numberOfReplicates, seed));
    return __result;
END_RCPP
}
